FROM python:3.9
WORKDIR /app
COPY requirements.txt .
RUN pip install -r requirements.txt
COPY . .
RUN pip install --upgrade Flask Flask-SQLAlchemy
RUN pip install mysqlclient

EXPOSE 80
CMD ["python", "app.py"]
