version: '3'
services:
  db:
    build:
      context: ./DB
      dockerfile: Dockerfile
    ports:
      - 3306:3306

  server:
    build:
      context: ./Server
      dockerfile: Dockerfile
    ports:
      - 80:80
    depends_on:
      - db
